### ISSUE TITLE
Can't install with Laravel 6.2

### ISSUE THREAD

**Issue by tulaeff** [rorecek/laravel-autoincrement#1]
`Using version ^1.0 for rorecek/laravel-autoincrement
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for rorecek/laravel-autoincrement ^1.0 -> satisfiable by rorecek/laravel-autoincrement[v1.0.0].
    - Conclusion: remove laravel/framework v6.5.1
    - Conclusion: don't install laravel/framework v6.5.1
    - rorecek/laravel-autoincrement v1.0.0 requires laravel/framework ^5.5 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v6.5.1].
    - Can only install one of: laravel/framework[5.6.x-dev, v6.5.1].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.5.1].
    - Can only install one of: laravel/framework[5.8.x-dev, v6.5.1].
    - Installation request for laravel/framework (locked at v6.5.1, required as ^6.2) -> satisfiable by laravel/framework[v6.5.1].

Installation failed, reverting ./composer.json to its original content.`

**Comment by rorecek** [comment]
It should be fixed with version 1.0.1 now. Thank you very much.
